Styling/homepage/horinzontal card test
Larissartoricader/Capstone pull request #81
Opened 2024-05-21 10:40 UTC by Larissartoricader

2024-05-21 13:10 UTC, F-Kirchhoff commented on components/NavigationBar.js
> +          <StyledHeartIcone />
typo: Icon

2024-05-21 13:12 UTC, F-Kirchhoff commented on components/RecipeCard.js
> +        ></StyledImage>
always use self closing tags if possible. Please check your codebase and update it accordingly.

2024-05-21 13:13 UTC, F-Kirchhoff commented on pages/index.js
> +      </TipOfTheDayWrapper> */}
remove this code as well.

2024-05-21 13:29 UTC, Larissartoricader commented on components/FilteredRecipes.js
> +          <label htmlFor="symptom"></label>
Done!

2024-05-21 13:31 UTC, Larissartoricader commented on components/FilteredRecipes.js
> +const StyledTextSuggestion = styled.p`
Done

2024-05-21 13:32 UTC, Larissartoricader commented on components/FilteredRecipes.js
> +                  key={index}
done

2024-05-21 13:34 UTC, Larissartoricader commented on components/FilteredRecipes.js
> +const StyledCross = styled.span`
done

2024-05-21 13:36 UTC, Larissartoricader commented on components/NavigationBar.js
> +          <StyledHomeIcone />
Done

2024-05-21 14:30 UTC, Larissartoricader commented on components/RecipeCard.js
> +        </StyledBookmarkIcon>
In THIS Case I needed both, but I got it. I will update the code if I see it again ;D

2024-05-21 14:37 UTC, F-Kirchhoff requested changes
Hey Herbies,
this looks better, but there is still one issue. please take a look.

2024-05-21 14:37 UTC, F-Kirchhoff commented on components/FilteredRecipes.js
> +                  key={uid()}
this is unfortunately not better. With every render you call uid again, generating a new id. This means that the key changes every render. Please use a fixed value from your data array, for example "suggestion". If suggestion is not unique, please update the data structure to include predefined ids.

Please keep in mind that you need to update this everywhere you use uid this way.

2024-05-22 12:34 UTC, Roland-Hufnagel approved these changes
LGTM

2024-05-23 08:10 UTC, F-Kirchhoff approved these changes

2024-05-23 08:11 UTC, merged